from dataclasses import dataclass
import json
import os
import re
import urllib.request
import urllib.error

@dataclass(frozen=True)
class GeneratedDocs:
    readme: str
    architecture: str
    used_llm: bool
    model: str

class LLMError(RuntimeError):
    pass

def _tag(text: str, name: str):
    match = re.search(rf'<{name}>\s*(.*?)\s*</{name}>', text, flags=re.DOTALL | re.IGNORECASE)
    return match.group(1).strip() if match else None

def call_openai_compatible(prompt: str, model: str, api_key: str, base_url: str) -> str:
    url = base_url.rstrip('/')
    if not url.endswith('/chat/completions'):
        url += '/chat/completions'
    payload = {
        'model': model,
        'messages': [
            {'role': 'system', 'content': 'You create accurate GitHub documentation from repository evidence.'},
            {'role': 'user', 'content': prompt},
        ],
        'temperature': 0.2,
    }
    req = urllib.request.Request(url, data=json.dumps(payload).encode(), headers={'Content-Type': 'application/json', 'Authorization': f'Bearer {api_key}'}, method='POST')
    try:
        with urllib.request.urlopen(req, timeout=90) as response:
            body = json.loads(response.read().decode())
        return body['choices'][0]['message']['content']
    except (urllib.error.URLError, KeyError, IndexError, json.JSONDecodeError) as exc:
        raise LLMError(f'LLM request failed: {exc}') from exc

def _prompt(summary) -> str:
    files = '\n\n'.join(f'## {f.path}\n```\n{f.preview}\n```' for f in summary.analyzed_files)
    return f'''Create README.md and ARCHITECTURE.md. Return exactly:\n<README>markdown</README>\n<ARCHITECTURE>markdown</ARCHITECTURE>\n\nTree:\n{summary.tree}\n\nImportant files:\n{summary.important_files}\n\nFiles:\n{files}'''

def generate_docs(summary, force_heuristic=False) -> GeneratedDocs:
    model = os.getenv('REPOPILOT_MODEL', 'gpt-4o-mini')
    api_key = os.getenv('REPOPILOT_API_KEY') or os.getenv('OPENAI_API_KEY')
    base_url = os.getenv('REPOPILOT_BASE_URL', 'https://api.openai.com/v1')
    if api_key and not force_heuristic:
        text = call_openai_compatible(_prompt(summary), model, api_key, base_url)
        readme = _tag(text, 'README')
        arch = _tag(text, 'ARCHITECTURE')
        if not readme or not arch:
            raise LLMError('LLM response missing README or ARCHITECTURE tags')
        return GeneratedDocs(readme, arch, True, model)
    return heuristic_docs(summary)

def heuristic_docs(summary) -> GeneratedDocs:
    name = os.path.basename(summary.root.rstrip(os.sep)) or 'Project'
    languages = ', '.join(summary.language_counts.keys()) or 'source files'
    important = '\n'.join(f'- `{p}`' for p in summary.important_files) or '- No common setup files detected.'
    readme = f'''# {name}\n\nGenerated by **RepoPilot**.\n\n## Overview\n\nThis appears to be a {languages} codebase. RepoPilot analyzed {len(summary.analyzed_files)} files out of {summary.total_files_seen} files.\n\n## Repository Highlights\n\n{important}\n\n## Project Structure\n\n```text\n{summary.tree}\n```\n\n## Getting Started\n\n1. Clone this repository.\n2. Install dependencies based on the setup files above.\n3. Run the project or tests using the commands documented in source files.\n'''
    arch = f'''# Architecture\n\nGenerated by **RepoPilot**.\n\n## Codebase Summary\n\nRepoPilot detected {summary.total_files_seen} files and analyzed {len(summary.analyzed_files)} text/code files.\n\n## File Map\n\n```text\n{summary.tree}\n```\n\n## Setup Signals\n\n{important}\n'''
    return GeneratedDocs(readme.strip(), arch.strip(), False, 'heuristic-no-api-key')
